/**
 * Hebrew display names for the built-in exercises (keyed by the stored English name).
 * Display only: the database, search, dictation and import keep using the English name.
 */
export const EXERCISE_NAMES_HE: Record<string, string> = {
  "Bench Press": "לחיצת חזה",
  "Incline Bench Press": "לחיצת חזה בשיפוע חיובי",
  "Incline Dumbbell Press": "לחיצת חזה בשיפוע עם משקולות",
  "Dumbbell Bench Press": "לחיצת חזה עם משקולות",
  "Chest Fly": "פרפר",
  "Cable Crossover": "קרוסאובר בכבלים",
  "Push-up": "שכיבות סמיכה",
  Dips: "מקבילים",
  "Overhead Press": "לחיצת כתפיים",
  "Dumbbell Shoulder Press": "לחיצת כתפיים עם משקולות",
  "Lateral Raise": "הרחקה לצדדים",
  "Face Pull": "פייס פול",
  "Rear Delt Fly": "פרפר הפוך",
  "Pull-up": "מתח",
  "Chin-up": "מתח באחיזה הפוכה",
  "Lat Pulldown": "פולי עליון",
  "Seated Cable Row": "חתירה בכבל בישיבה",
  "Barbell Row": "חתירה במוט",
  "Dumbbell Row": "חתירה עם משקולת",
  "T-Bar Row": "חתירת T",
  Deadlift: "דדליפט",
  "Barbell Curl": "כפיפת מרפקים במוט",
  "Dumbbell Curl": "כפיפת מרפקים עם משקולות",
  "Hammer Curl": "פטישים",
  "Triceps Pushdown": "פשיטת מרפקים בפולי",
  "Overhead Triceps Extension": "פשיטת מרפקים מעל הראש",
  "Skull Crusher": "סקול קראשר",
  Squat: "סקוואט",
  "Front Squat": "סקוואט קדמי",
  "Leg Press": "לחיצת רגליים",
  "Romanian Deadlift": "דדליפט רומני",
  "Bulgarian Split Squat": "סקוואט בולגרי",
  Lunge: "מכרעים",
  "Leg Extension": "פשיטת ברכיים",
  "Leg Curl": "כפיפת ברכיים",
  "Hip Thrust": "היפ טראסט",
  "Calf Raise": "הרמות עקבים",
  "Goblet Squat": "סקוואט גביע",
  "Kettlebell Swing": "סווינג קטלבל",
  Plank: "פלאנק",
  "Hanging Leg Raise": "הרמות רגליים בתלייה",
  "Cable Crunch": "כפיפות בטן בכבל",
  Running: "ריצה",
  Treadmill: "הליכון",
  Walking: "הליכה",
  "Stationary Bike": "אופני כושר",
  Elliptical: "אליפטיקל",
  "Rowing Machine": "מכונת חתירה",
  "Stair Climber": "מדרגות",
  "Jump Rope": "קפיצה בחבל",
};
