name = "calil-watchdog"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "32616ba605b048f58af65179bde7abbe"

[vars]
ALERT_EMAIL = "baryagel64@gmail.com"
